AWSTemplateFormatVersion: '2010-09-09'
Resources:
  PetShopApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: PetShopApi
      Description: API for Pet Shop
      EndpointConfiguration:
        Types:
          - REGIONAL
      FailOnWarnings: 'false'

  DevStage:
    Type: 'AWS::ApiGateway::Stage'
    Properties:
      DeploymentId: !Ref PetShopApiDeployment
      RestApiId: !Ref PetShopApi
      StageName: dev

  ProdStage:
    Type: 'AWS::ApiGateway::Stage'
    Properties:
      DeploymentId: !Ref PetShopApiDeployment
      RestApiId: !Ref PetShopApi
      StageName: prod

  PetShopApiDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    DependsOn: PetShopApi
    Properties:
      RestApiId: !Ref PetShopApi

  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt [ApiGatewayLoggingRole, Arn]

  ApiGatewayLoggingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: ApiGatewayLoggingPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:DescribeLogGroups
                  - logs:PutLogEvents
                Resource: '*'

Outputs:
  RestApiId:
    Description: The ID of the API Gateway
    Value: !Ref PetShopApi
