AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  PetShopApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: PetShopApi
      StageName: Prod

  UsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: ../zipped-lambdas/users.zip
      Events:
        Users:
          Type: Api
          Properties:
            Path: /users
            Method: ANY
            RestApiId: !Ref PetShopApi

  OrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: ../zipped-lambdas/orders.zip
      Events:
        Orders:
          Type: Api
          Properties:
            Path: /orders
            Method: ANY
            RestApiId: !Ref PetShopApi
