name: CI/CD pipeline

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test

  build-and-deploy:
    needs: [lint, test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Bundle lambdas
        run: |
          bash ./scripts/bundle-lambdas.sh 

      - name: Deploy to AWS
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            ENVIRONMENT=prod
          else
            ENVIRONMENT=dev
          fi
          bash ./scripts/deploy.sh $ENVIRONMENT
